---
title: "JD_HW5"
author: "Jennifer Deaton"
date: "2026-03-20"
output: html_document
---

knitr::opts_chunk$set(echo = TRUE)

# load libraries 
```{r}
library(ggplot2)
library(dplyr)
library(mapdata)
```

# load map data
```{r}
states = map_data("state")
```

# filter to california
```{r}
california = states %>% filter(region == "california")
```

# view head
```{r}
head(california)
```

# create california with ggplot and geom_polygon
```{r}
ggplot() + geom_polygon(data = california,aes(x = long, y = lat, group = group),fill = "pink",color = "black") + coord_fixed(1.3) + theme_minimal()
```

# load turbine data
```{r}
load("/Users/jenniferdeaton/Desktop/wind_turbines.rda")
```

# filter to california
```{r}
wind_ca = wind_turbines %>% filter(t_state == "CA")
```

# plot turbines
```{r}
ggplot() + geom_polygon(data = california,aes(x = long, y = lat, group = group),fill = "pink",color = "black") +geom_point(data = wind_ca,aes(x = xlong, y = ylat),color = "blue",size = 1.5) + coord_fixed(1.3) + theme_minimal()
```





